export const DEFAULT_ATTENTION_LAYERS = 4
export const DEFAULT_CONTEXT_SIZE = 3
export const DEFAULT_EMBEDDING_DIMENSION = 64
export const DEFAULT_GENERATION_LENGTH = 15
export const DEFAULT_TEMPERATURE = 0.7
export const DEFAULT_TOP_P = 0.9
